version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore
    environment:
      FLASK_APP: app:create_app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:password@localhost/bookstore
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
